server:
  port: 9527

spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的ip地址
        namespace: 8b33c3f1-637c-4c73-9491-ae4e3b399aa1
        group: DEFAULT_GROUP # 网关只能转发同gruop的
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel dashboard地址
        port: 8719 # 默认8719端口，如被占用会向上+1直到找到空闲端口
      eager: true
    gateway:
      discovery:
        locator:
          enabled: true # 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
      routes:
        - id: routh_payment # 唯一就行
          uri: lb://nacos-provider # 网关帮我们转发的真实url，lb负载均衡，//后边服务名
          predicates:
            - Path=/payment/nacos/** # 匹配规则，Path首字母要大写

        - id: routh_rabbit
          uri: lb://rabbit-provider
          predicates:
            - Path=/provider/**



