server:
  port: 8801

spring:
  profiles:
    active: dev
  application:
    name: rabbit-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的ip地址
        namespace: 8b33c3f1-637c-4c73-9491-ae4e3b399aa1
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel dashboard地址
        port: 8719 # 默认8719端口，如被占用会向上+1直到找到空闲端口
      eager: true
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        sms-out-0: # 自定义生产者通道名称
          destination: sms-topic # 自定义Exchange交换机名称，生产者和消费者需要配置同一个Exchange
          content-type: application/json # 消息类型

management:
  endpoints:
    web:
      exposure:
        include: '*'