server:
  port: 9003

spring:
  profiles:
    active: dev
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的ip地址
        namespace: 8b33c3f1-637c-4c73-9491-ae4e3b399aa1
        group: DEFAULT_GROUP

management:
  endpoints:
    web:
      exposure:
        include: '*'



