server:
  port: 84

spring:
  profiles:
    active: dev
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos的ip地址
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel dashboard地址
        port: 8719 # 默认8719端口，如被占用会向上+1直到找到空闲端口

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true

